---

version: '3.7'

services:
  web:
    image: rathaheang/httpd-php:7.3
    environment:
      LOCAL_USER_ID: 1001
    volumes:
      - .:/var/www/html
      - ./httpd-php/docker/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./httpd-php/docker/php.ini:/etc/php/7.3/apache2/php.ini
    ports:
      - 80:80
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  db-data:
